global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:
scrape_configs:
 - job_name: goetia
   static_configs:
   - targets: [
       'goetia:50051',
       'goetia:8080',
   ]